name: iti_gen
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py38h130f0dd_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=9.4.0=py38h6a678d5_0
  - pip=20.3.3=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_0
  - setuptools=68.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.12.0=py38_cu113
  - typing_extensions=4.7.1=py38h06a4308_0
  - urllib3=1.26.16=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - annotated-types==0.5.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - arrow==1.2.3
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backoff==2.2.1
    - beautifulsoup4==4.12.2
    - blessed==1.20.0
    - cachetools==5.3.1
    - click==8.1.7
    - croniter==1.4.1
    - dateutils==0.6.12
    - deepdiff==6.5.0
    - diffusers==0.12.1
    - einops==0.6.1
    - exceptiongroup==1.1.3
    - fastapi==0.103.1
    - filelock==3.12.4
    - frozenlist==1.4.0
    - fsspec==2023.9.1
    - ftfy==6.1.1
    - google-auth==2.23.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.58.0
    - h11==0.14.0
    - huggingface-hub==0.17.1
    - imhist==0.0.4
    - importlib-metadata==6.8.0
    - imwatermark==0.0.2
    - inquirer==3.1.3
    - invisible-watermark==0.2.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - kornia==0.6.8
    - lightning==2.0.9
    - lightning-cloud==0.5.38
    - lightning-utilities==0.9.0
    - markdown==3.4.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mdurl==0.1.2
    - multidict==6.0.4
    - numpy==1.24.4
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - opencv-python==4.8.0.76
    - ordered-set==4.1.0
    - packaging==23.1
    - protobuf==4.24.3
    - psutil==5.9.5
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==2.1.1
    - pydantic-core==2.4.0
    - pydeprecate==0.3.2
    - pygments==2.16.1
    - pyjwt==2.8.0
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - python-multipart==0.0.6
    - pytorch-lightning==1.7.7
    - pytz==2023.3.post1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - readchar==4.0.5
    - regex==2023.8.8
    - requests-oauthlib==1.3.1
    - rich==13.5.3
    - rsa==4.9
    - sniffio==1.3.0
    - soupsieve==2.5
    - starlette==0.27.0
    - starsessions==1.3.0
    - taming-transformers-rom1504==0.0.6
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - tokenizers==0.12.1
    - torchmetrics==0.10.0
    - tqdm==4.66.1
    - traitlets==5.10.0
    - transformers==4.19.2
    - uvicorn==0.23.2
    - wcwidth==0.2.6
    - websocket-client==1.6.3
    - websockets==11.0.3
    - werkzeug==2.3.7
    - yarl==1.9.2
    - zipp==3.16.2
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip